src/Entity/Travels.php
<?php

namespace App\Entity;

use App\Repository\TravelsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TravelsRepository::class)]
class Travels
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 255)]
    private ?string $town = null;

    #[ORM\Column(length: 255)]
    private ?string $hotel = null;

    #[ORM\Column]
    private ?int $days = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    #[ORM\Column]
    private ?bool $all_included = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne]
    public ?Status $fk_status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): static
    {
        $this->town = $town;

        return $this;
    }

    public function getHotel(): ?string
    {
        return $this->hotel;
    }

    public function setHotel(string $hotel): static
    {
        $this->hotel = $hotel;

        return $this;
    }

    public function getDays(): ?int
    {
        return $this->days;
    }

    public function setDays(int $days): static
    {
        $this->days = $days;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isAllIncluded(): ?bool
    {
        return $this->all_included;
    }

    public function setAllIncluded(bool $all_included): static
    {
        $this->all_included = $all_included;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFkStatus(): ?Status
    {
        return $this->fk_status;
    }

    public function setFkStatus(?Status $fk_status): static
    {
        $this->fk_status = $fk_status;

        return $this;
    }
}

src/Form/TravelsType.php
<?php

namespace App\Form;


// use App\Entity\Status as EntityStatus;
use App\Entity\Travels;
use App\Entity\Status;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;

use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\Request;


class TravelsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('country', TextType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'mardin-bottom:15px']
            ])
            ->add('town', TextType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'mardin-bottom:15px']
            ])
            ->add('hotel', TextType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'mardin-bottom:15px']
            ])
            ->add('days', NumberType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'mardin-bottom:15px']
            ])
            ->add('price', NumberType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px', 'step' => '0.1']
            ])
            ->add('all_included', ChoiceType::class, [
                'choices' => ['yes' => 1, 'no' => 0],
                'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
            ])
            // ->add('created_at')
            ->add('picture', TextType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
            ])
            ->add('description', TextareaType::class, [
                'attr' => ['class' => 'form-control', 'style' => 'margin-bottom:15px']
            ])
            ->add('fk_status', EntityType::class, [
                'class' => Status::class,
                'choice_label' => 'name',
                'attr' => ['class' => 'form-control mb-3']
            ])
            ->add('picture', FileType::class, [
                'attr' => ['class' => 'form-control'],
                'label' => 'Upload Picture',
                //unmapped means that is not associated to any entity property
                'mapped' => false,
                // mandatory to have a file
                'required' => true,

                //in the associated entity, so you can use the PHP constraint classes as validators
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                            'image/jpg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image file',
                    ])
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Travels::class,
        ]);
    }
}

src/Controller/TravelsController.php
<?php

namespace App\Controller;

use App\Entity\Travels;
use App\Form\TravelsType;
use App\Repository\TravelsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\FileUploader;



#[Route('/')]
class TravelsController extends AbstractController
{
    #[Route('/', name: 'app_travels_index', methods: ['GET'])]
    public function index(TravelsRepository $travelsRepository): Response
    {
        return $this->render('travels/index.html.twig', [
            'travels' => $travelsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_travels_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $travel = new Travels();
        $form = $this->createForm(TravelsType::class, $travel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $pictureFileName = $fileUploader->upload($pictureFile);
                $travel->setPicture($pictureFileName);
            }
            $now = new \DateTimeImmutable();
            $travel->setCreatedAt($now);
            $entityManager->persist($travel);
            $entityManager->flush();

            return $this->redirectToRoute('app_travels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('travels/new.html.twig', [
            'travel' => $travel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_travels_show', methods: ['GET'])]
    public function show(Travels $travel): Response
    {
        return $this->render('travels/show.html.twig', [
            'travel' => $travel,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_travels_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Travels $travel, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(TravelsType::class, $travel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $pictureFileName = $fileUploader->upload($pictureFile);
                $travel->setPicture($pictureFileName);
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_travels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('travels/edit.html.twig', [
            'travel' => $travel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_travels_delete', methods: ['POST'])]
    public function delete(Request $request, Travels $travel, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $travel->getId(), $request->request->get('_token'))) {
            $entityManager->remove($travel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_travels_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/travels/_delete_form.html.twig
<form method="post" action="{{ path('app_travels_delete', { id: travel.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ travel.id) }}" />
  <button class="btn btn-danger mt-4">Delete</button>
</form>

templates/travels/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-success mt-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/travels/edit.html.twig
{% extends 'base.html.twig' %} {% block title %}Edit Travels{% endblock %} {% block body %}
<div class="container my-5 pt-5">
  <h1>Edit Travels</h1>

  {{ include('travels/_form.html.twig', { button_label: 'Update' }) }}

  <a class="btn mt-4" href="{{ path('app_travels_index') }}#{{ travel.id }}">back to list</a>
  {{ include('travels/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/travels/index.html.twig
{% extends 'base.html.twig' %} {% block title %}Travels | {{ parent() }}{% endblock %} {% block body %} {% block stylesheets %} {% endblock %}

<div class="container my-5 pt-5">
  <h1 class="mb-4">Travel destinations</h1>
  <div class="row row-cols-xs-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-3">
    {% for travel in travels %}
    <div id="{{ travel.id }}" class="mb-4">
      <div class="col">
        <div class="card h-100">
          <img src="{{ asset('pictures/'~ travel.picture) }}" class="card-img-top object-fit-cover rounded-top asprat" alt="{{ travel.country }}" />
          <div class="card-body">
            <h5 class="card-title mb-3">{{ travel.country }}</h5>
            <p class="card-text my-1">Town: {{ travel.town }}</p>
            <p class="card-text">Days: {{ travel.days }}</p>
            {#
            <p class="card-text text-warning">&starf;&starf;&starf;&starf;&star;</p>
            #}
            <div class="btn-group rounded w-100" role="group" aria-label="Basic example">
              <a class="btn btn-sm rounded-start btn-info" href="{{ path('app_travels_show', { id: travel.id }) }}">View</a>
              <a class="btn btn-sm rounded-end btn-warning" href="{{ path('app_travels_edit', { id: travel.id }) }}">Edit</a>
              {# <a class="btn btn-sm rounded-end btn-danger" href="/delete/{{ travel.id }}">Delete</a> #}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <p class="text-body-secondary">No records found ¯\_(ツ)_/¯</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/travels/new.html.twig
{% extends 'base.html.twig' %} {% block title %}New Destination | {{ parent() }}{% endblock %} {% block body %}
<div class="container my-5 pt-5">
  <h1>Create new Travels</h1>

  {{ include('travels/_form.html.twig') }}

  {# <a href="{{ path('app_travels_index') }}">back to list</a> #}
</div>
{% endblock %}

templates/travels/show.html.twig
{% extends 'base.html.twig' %} {% block title %}Travels{% endblock %} {% block body %}

<div class="container my-5 pt-5">
  <div class="card h-100">
    <div class="card-body">
      <h2 class="card-title mb-3">{{ travel.country }}</h2>
      <p class="card-text my-1">Town: {{ travel.town }}</p>
      <p class="card-text my-1">Hotel: {{ travel.hotel }}</p>
      <p class="card-text my-1">Days: {{ travel.days }}</p>
      <p class="card-text my-1">All included: {{ travel.allIncluded ? 'Yes' : 'No' }}</p>
      <p class="card-text">Price: &euro;{{ travel.price }}</p>
      <p class="card-text my-1">{{ travel.description }}</p>
      <p class="card-text my-1 text-{{travel.fk_status.name == "Done" ? "success" : "body-secondary"}} ">{{ travel.fk_status.name }}</p>
      <p class="my-3 text-body-secondary">
        <small>Added at: {{ travel.createdAt ? travel.createdAt|date('Y-m-d H:i:s') : '' }}</small>
      </p>
      
      <div class="btn-group w-100" role="group" aria-label="Basic example">
        <a class="btn btn-sm btn-info" href="{{ path('app_travels_index') }}#{{ travel.id }}">Back to list</a>
        <a class="btn btn-sm btn-warning" href="{{ path('app_travels_edit', { id: travel.id }) }}">Edit</a>
      </div>
    </div>
    {##}
    <img src="{{ asset('pictures/'~ travel.picture) }}" class="card-img-top object-fit-cover rounded-bottom asprat" alt="..." />
  </div>
</div>

{# {{ include('travels/_delete_form.html.twig') }} #} {% endblock %}